apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: infra
  finalizers:
    # https://argo-cd.readthedocs.io/en/latest/user-guide/app_deletion/#about-the-deletion-finalizer
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: '3.4.4' # = v1.14.4
    chart: kyverno
    helm:
      releaseName: kyverno
      parameters:
        # https://kyverno.io/docs/installation/methods/#high-availability-installation
        - name: admissionController.replicas
          value: "3"
        - name: backgroundController.replicas
          value: "3"
        - name: cleanupController.replicas
          value: "3"
        - name: reportsController.replicas
          value: "3"
  sources: []
  project: infra
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
