apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra.kyverno
  namespace: argocd
  finalizers: []
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: ''
    chart: kyverno
  sources: []
  project: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
