apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: infra
  finalizers: []
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: '3.4.4' # = v1.14.4
    chart: kyverno
    helm:
      releaseName: kyverno
  sources: []
  project: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
