apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policy-reporter
  namespace: infra
  finalizers: []
spec:
  destination:
    namespace: policy-reporter
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kyverno.github.io/policy-reporter
    targetRevision: '3.4.4' # = v1.14.4
    chart: policy-reporter
    helm:
      releaseName: policy-reporter
      # https://kyverno.github.io/policy-reporter-docs/getting-started/installation.html#base-ui-kyverno-plugin-installation
      parameters:
        - name: ui.enabled
          value: "true"
          type: boolean
        - name: plugin.kyverno.enabled
          value: "true"
          type: boolean
  sources: []
  project: infra
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
