apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  source:
    path: apps/infra
    repoURL: https://github.com/kristoferlundgren/argocd-autopilot-test.git
    targetRevision: main
  sources: []
  project: infra
  syncPolicy:
    automated: null
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
